/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee { 'id' : bigint, 'name' : string }
export interface ShiftTipRecord {
  'paidEmployeeIds' : Array<bigint>,
  'weekKey' : string,
  'sharePerEmployee' : number,
  'dayIndex' : bigint,
  'shiftIndex' : bigint,
  'employeeIds' : Array<bigint>,
  'poolAmount' : number,
}
export interface _SERVICE {
  'addEmployee' : ActorMethod<[string], bigint>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'getUnpaidRecords' : ActorMethod<[], Array<ShiftTipRecord>>,
  'getWeekData' : ActorMethod<[string], Array<ShiftTipRecord>>,
  'listArchivedWeekKeys' : ActorMethod<[], Array<string>>,
  'listEmployees' : ActorMethod<[], Array<Employee>>,
  'markTipsPaid' : ActorMethod<
    [string, bigint, bigint, Array<bigint>],
    undefined
  >,
  'saveShiftTip' : ActorMethod<
    [string, bigint, bigint, number, Array<bigint>],
    undefined
  >,
  'updateEmployee' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];