/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShiftTipRecord = IDL.Record({
  'paidEmployeeIds' : IDL.Vec(IDL.Nat),
  'weekKey' : IDL.Text,
  'sharePerEmployee' : IDL.Float64,
  'dayIndex' : IDL.Nat,
  'shiftIndex' : IDL.Nat,
  'employeeIds' : IDL.Vec(IDL.Nat),
  'poolAmount' : IDL.Float64,
});
export const Employee = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'addEmployee' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'getUnpaidRecords' : IDL.Func([], [IDL.Vec(ShiftTipRecord)], ['query']),
  'getWeekData' : IDL.Func([IDL.Text], [IDL.Vec(ShiftTipRecord)], ['query']),
  'listArchivedWeekKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'markTipsPaid' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'saveShiftTip' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'updateEmployee' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShiftTipRecord = IDL.Record({
    'paidEmployeeIds' : IDL.Vec(IDL.Nat),
    'weekKey' : IDL.Text,
    'sharePerEmployee' : IDL.Float64,
    'dayIndex' : IDL.Nat,
    'shiftIndex' : IDL.Nat,
    'employeeIds' : IDL.Vec(IDL.Nat),
    'poolAmount' : IDL.Float64,
  });
  const Employee = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  
  return IDL.Service({
    'addEmployee' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'getUnpaidRecords' : IDL.Func([], [IDL.Vec(ShiftTipRecord)], ['query']),
    'getWeekData' : IDL.Func([IDL.Text], [IDL.Vec(ShiftTipRecord)], ['query']),
    'listArchivedWeekKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'markTipsPaid' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'saveShiftTip' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'updateEmployee' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };