/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShiftTipRecord {
    paidEmployeeIds: Array<bigint>;
    weekKey: string;
    sharePerEmployee: number;
    dayIndex: bigint;
    shiftIndex: bigint;
    employeeIds: Array<bigint>;
    poolAmount: number;
}
export interface Employee {
    id: bigint;
    name: string;
}
export interface backendInterface {
    addEmployee(name: string): Promise<bigint>;
    deleteEmployee(id: bigint): Promise<void>;
    getUnpaidRecords(): Promise<Array<ShiftTipRecord>>;
    getWeekData(weekKey: string): Promise<Array<ShiftTipRecord>>;
    listArchivedWeekKeys(): Promise<Array<string>>;
    listEmployees(): Promise<Array<Employee>>;
    markTipsPaid(weekKey: string, dayIndex: bigint, shiftIndex: bigint, employeeIds: Array<bigint>): Promise<void>;
    saveShiftTip(weekKey: string, dayIndex: bigint, shiftIndex: bigint, poolAmount: number, employeeIds: Array<bigint>): Promise<void>;
    updateEmployee(id: bigint, name: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEmployee(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async getUnpaidRecords(): Promise<Array<ShiftTipRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpaidRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpaidRecords();
            return result;
        }
    }
    async getWeekData(arg0: string): Promise<Array<ShiftTipRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeekData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeekData(arg0);
            return result;
        }
    }
    async listArchivedWeekKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listArchivedWeekKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArchivedWeekKeys();
            return result;
        }
    }
    async listEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployees();
            return result;
        }
    }
    async markTipsPaid(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTipsPaid(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTipsPaid(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveShiftTip(arg0: string, arg1: bigint, arg2: bigint, arg3: number, arg4: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveShiftTip(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveShiftTip(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateEmployee(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
